# Serverless definition file
# --------------------------
# Defines Lambda functions to be deployed to AWS using the Serverless Framework.
# http://serverless.com

service: database-service

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128
  timeout: 30

functions:
  # Get users ----------------------------------------------------------------
  getUsers:
    handler: index.getUsers
    events:
      - http:
          path: users
          method: get
          cors: 
            origins:               
              - '*'            